version: "3"

services:
  postgresql:
    image: postgres:16-alpine3.20
    ports:
      - "5432:5432"
    volumes:
      - "./backend/db/db.sql:/docker-entrypoint-initdb.d/db.sql"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
